name: Test
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
      - run: dotnet build --configuration ${{ matrix.configuration }}
      - run: dotnet test DigitalOcean.API.Tests/ --no-build --configuration ${{ matrix.configuration }}
